import { PLATFORM_CATEGORY_SLUG } from "../src/config/constants.js";

export { PLATFORM_CATEGORY_SLUG };

function categoryCard(slug: string) {
  return `/assets/categories/${slug}.jpg`;
}

function categoryBanner(slug: string) {
  return `/assets/categories/${slug}-banner.jpg`;
}

const nestedParentMain: Record<string, string> = {
  "vehicle-rental": "rental-hire",
  "electronics-rental": "rental-hire",
  "event-equipment": "rental-hire",
  "outdoor-travel": "rental-hire",
  "tools-equipment": "rental-hire",
  "furniture-rental": "rental-hire",
  electrical: "home-property",
  "plumbing-items": "home-property",
  "mechanical-hardware": "home-property",
  "home-decor": "home-property",
  furniture: "home-property",
  "paint-coatings": "home-property",
  "building-materials": "home-property",
  clothing: "fashion-apparel",
  shoes: "fashion-apparel",
  textiles: "fashion-apparel",
  "bags-accessories": "fashion-apparel",
  "auto-parts": "automotive",
  tyres: "automotive",
  batteries: "automotive",
  "auto-accessories": "automotive",
  "electronics-wholesale": "electronics-technology",
  "mobiles-accessories": "electronics-technology",
  "cctv-equipment": "electronics-technology",
  "computer-hardware": "electronics-technology",
};

function mediaForCategory(slug: string) {
  const mainSlug = nestedParentMain[slug] ?? slug;
  return {
    imageUrl: categoryCard(mainSlug),
    bannerUrl: categoryBanner(mainSlug),
  };
}

export type MainCategorySeed = {
  name: string;
  slug: string;
  icon: string;
  sortOrder: number;
  description: string;
  imageUrl: string;
  bannerUrl: string;
  kind: "supplier" | "service";
};

export type SubCategorySeed = {
  name: string;
  slug: string;
  parentSlug: string;
  icon: string;
  sortOrder: number;
  description: string;
  imageUrl: string;
  bannerUrl: string;
  kind: "supplier" | "service";
};

export type FieldSeed = {
  key: string;
  label: string;
  fieldType:
    | "text"
    | "textarea"
    | "number"
    | "boolean"
    | "select"
    | "multiselect"
    | "phone"
    | "asset_ref"
    | "asset_gallery";
  scope: "listing" | "service" | "business";
  required?: boolean;
  helpText?: string;
  placeholder?: string;
  section?: string;
  sortOrder: number;
  options?: string[];
  validation?: { min?: number; max?: number; minLength?: number; maxLength?: number };
  conditionalRules?: { fieldKey: string; equals?: string | number | boolean | null };
};

export const phase1Mains: MainCategorySeed[] = [
  {
    name: "Home & Properties",
    slug: "home-property",
    icon: "home_repair_service",
    sortOrder: 1,
    kind: "supplier",
    description:
      "Tradespeople for electrical, plumbing, and home jobs — rates and trade enquiries. Materials shops sit alongside with product types like cement and pipes.",
    ...mediaForCategory("home-property"),
  },
  {
    name: "Fashion & Apparel",
    slug: "fashion-apparel",
    icon: "checkroom",
    sortOrder: 2,
    kind: "supplier",
    description: "Clothing, footwear, textiles, and accessories — browse by product type and brand.",
    ...mediaForCategory("fashion-apparel"),
  },
  {
    name: "Automotive",
    slug: "automotive",
    icon: "directions_car",
    sortOrder: 3,
    kind: "supplier",
    description:
      "Car and bike repair, wash, and towing — rates and trade enquiries. Auto parts and tyre shops sit alongside.",
    ...mediaForCategory("automotive"),
  },
  {
    name: "Electronics & Technology",
    slug: "electronics-technology",
    icon: "devices",
    sortOrder: 4,
    kind: "supplier",
    description:
      "Phone, laptop, CCTV, and IT repair — rates and trade enquiries. Wholesale electronics shops sit alongside.",
    ...mediaForCategory("electronics-technology"),
  },
  {
    name: "Professional & Business",
    slug: "professional-business",
    icon: "business_center",
    sortOrder: 5,
    kind: "supplier",
    description:
      "CAs, lawyers, tax and business consultants — engagements, rates, and professional enquiries. Office supplies and print shops sit alongside.",
    ...mediaForCategory("professional-business"),
  },
  {
    name: "Health & Wellness",
    slug: "health-wellness",
    icon: "medical_services",
    sortOrder: 6,
    kind: "supplier",
    description:
      "Dentists, clinics, physio, and spa care — treatments, rates, and health enquiries. Medical and wellness product shops sit alongside.",
    ...mediaForCategory("health-wellness"),
  },
  {
    name: "Education & Training",
    slug: "education-training",
    icon: "school",
    sortOrder: 7,
    kind: "supplier",
    description:
      "Coaching, tuition, and training — courses, rates, and education enquiries. Books and stationery shops sit alongside.",
    ...mediaForCategory("education-training"),
  },
  {
    name: "Events & Lifestyle",
    slug: "events-lifestyle",
    icon: "celebration",
    sortOrder: 8,
    kind: "supplier",
    description: "Event crews, photographers, caterers, and wedding teams — packages, rates, and event enquiries. Jewellery and décor shops sit alongside.",
    ...mediaForCategory("events-lifestyle"),
  },
  {
    name: "Logistics & Other Services",
    slug: "logistics-other",
    icon: "local_shipping",
    sortOrder: 9,
    kind: "supplier",
    description: "Courier, packers & movers, transporters, and security — vehicles, rates, and move enquiries. Packing and scrap shops sit alongside.",
    ...mediaForCategory("logistics-other"),
  },
  {
    name: "Hotels, Resorts & Stays",
    slug: "hotels-resorts-stays",
    icon: "hotel",
    sortOrder: 10,
    kind: "service",
    description: "Hotels, resorts, homestays, villas, and cottages — rooms, rates, and stay enquiries.",
    ...mediaForCategory("hotels-resorts-stays"),
  },
  {
    name: "Rental & Hire",
    slug: "rental-hire",
    icon: "key",
    sortOrder: 11,
    kind: "supplier",
    description: "Hire vehicles, tools, furniture, and event equipment by the hour or day — rates, deposits, and hire enquiries.",
    ...mediaForCategory("rental-hire"),
  },
  {
    name: "Travel, Taxi & Transport",
    slug: "travel-taxi-transport",
    icon: "local_taxi",
    sortOrder: 12,
    kind: "service",
    description: "Taxi, cab, airport transfers, tours, and chauffeur trips — vehicles, rates, and trip enquiries.",
    ...mediaForCategory("travel-taxi-transport"),
  },
];

export const phase1Subs: SubCategorySeed[] = [
  ...namedSubs("home-property", [
    ["Electrical", "electrical", "electrical_services"],
    ["Plumbing items", "plumbing-items", "plumbing"],
    ["Mechanical & hardware", "mechanical-hardware", "handyman"],
    ["Home decor", "home-decor", "chair"],
    ["Furniture", "furniture", "weekend"],
    ["Paint & coatings", "paint-coatings", "format_paint"],
    ["Building materials", "building-materials", "apartment"],
  ]).map((sub) => ({
    ...sub,
    description: `Browse ${sub.name.toLowerCase()} by product type and brand — bulk, by order, or single piece.`,
  })),
  ...namedSubs("electrical", [
    ["Wires & cables", "wires-cables", "electrical_services"],
    ["Switches & sockets", "switches-sockets", "toggle_on"],
    ["Lighting", "lighting", "lightbulb"],
    ["Panels & MCBs", "panels-mcbs", "developer_board"],
  ]),
  ...namedSubs("plumbing-items", [
    ["Pipes & fittings", "pipes-fittings", "plumbing"],
    ["Bathroom fittings", "bathroom-fittings", "bathtub"],
    ["Tanks", "tanks", "water_drop"],
    ["Pumps", "pumps", "water"],
    ["Valves", "valves", "tune"],
  ]),
  ...namedSubs("building-materials", [
    ["Cement", "cement", "apartment"],
    ["Steel", "steel", "construction"],
    ["Bricks", "bricks", "wall_art"],
    ["Sand & aggregates", "sand-aggregates", "landscape"],
    ["Tiles", "tiles", "grid_view"],
    ["Roofing", "roofing", "roofing"],
  ]),
  ...namedSubs("mechanical-hardware", [
    ["Hand tools", "hand-tools", "handyman"],
    ["Fasteners", "fasteners", "build"],
    ["Locks & hardware", "locks-hardware", "lock"],
  ]),
  ...namedSubs("paint-coatings", [
    ["Interior paints", "interior-paints", "format_paint"],
    ["Exterior paints", "exterior-paints", "format_paint"],
    ["Primers & coatings", "primers-coatings", "brush"],
  ]),
  ...namedSubs("furniture", [
    ["Home furniture", "home-furniture-shop", "chair"],
    ["Office furniture", "office-furniture-shop", "desk"],
  ]),
  ...namedSubs("home-decor", [
    ["Soft furnishings", "soft-furnishings", "weekend"],
    ["Wall decor", "wall-decor", "wallpaper"],
  ]),
  ...namedSubs(
    "home-property",
    [
      ["Electricians", "electricians", "electrical_services"],
      ["Plumbers", "plumbers", "plumbing"],
      ["AC Services", "ac-services", "ac_unit"],
      ["Interior Designers", "interior-designers", "chair"],
      ["Painting Contractors", "painting-contractors", "format_paint"],
      ["Carpenter Services", "carpenter-services", "handyman"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("fashion-apparel", [
    ["Clothing / garments", "clothing", "checkroom"],
    ["Shoes / footwear", "shoes", "steps"],
    ["Textiles", "textiles", "weekend"],
    ["Bags & accessories", "bags-accessories", "shopping_bag"],
  ]).map((sub) => ({
    ...sub,
    description: `Browse ${sub.name.toLowerCase()} by type and brand.`,
  })),
  ...namedSubs("clothing", [
    ["Men", "clothing-men", "checkroom"],
    ["Women", "clothing-women", "checkroom"],
    ["Kids", "clothing-kids", "child_care"],
    ["Workwear", "clothing-workwear", "work"],
  ]),
  ...namedSubs("shoes", [
    ["Men footwear", "shoes-men", "steps"],
    ["Women footwear", "shoes-women", "steps"],
    ["Kids footwear", "shoes-kids", "child_care"],
    ["Sports footwear", "shoes-sports", "sports_soccer"],
  ]),
  ...namedSubs("automotive", [
    ["Auto parts", "auto-parts", "settings"],
    ["Tyres", "tyres", "tire_repair"],
    ["Batteries", "batteries", "battery_charging_full"],
    ["Accessories", "auto-accessories", "directions_car"],
  ]).map((sub) => ({
    ...sub,
    description: `Browse ${sub.name.toLowerCase()} by type and brand.`,
  })),
  ...namedSubs("auto-parts", [
    ["Engine parts", "engine-parts", "settings"],
    ["Body parts", "body-parts", "directions_car"],
    ["Filters & oils", "filters-oils", "oil_barrel"],
    ["Brake parts", "brake-parts", "car_crash"],
  ]),
  ...namedSubs("tyres", [
    ["Car tyres", "car-tyres", "tire_repair"],
    ["Bike tyres", "bike-tyres", "two_wheeler"],
  ]),
  ...namedSubs("batteries", [
    ["Car batteries", "car-batteries", "battery_charging_full"],
    ["Inverter batteries", "inverter-batteries", "battery_full"],
  ]),
  ...namedSubs(
    "automotive",
    [
      ["Car Repair & Services", "car-repair-services", "car_repair"],
      ["Bike Repair & Services", "bike-repair-services", "two_wheeler"],
      ["Car Wash & Detailing", "car-wash-detailing", "local_car_wash"],
      ["Vehicle Towing", "vehicle-towing", "rv_hookup"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("electronics-technology", [
    ["Electronics wholesale", "electronics-wholesale", "devices"],
    ["Mobiles & accessories", "mobiles-accessories", "phone_iphone"],
    ["CCTV equipment", "cctv-equipment", "videocam"],
    ["Computer hardware", "computer-hardware", "computer"],
  ]).map((sub) => ({
    ...sub,
    description: `Browse ${sub.name.toLowerCase()} by type and brand.`,
  })),
  ...namedSubs("mobiles-accessories", [
    ["Phones", "phones", "phone_iphone"],
    ["Chargers & cables", "chargers-cables", "cable"],
    ["Cases & covers", "cases-covers", "phone_iphone"],
  ]),
  ...namedSubs("computer-hardware", [
    ["Laptops", "laptops", "laptop"],
    ["Desktops & components", "desktops-components", "computer"],
    ["Peripherals", "peripherals", "mouse"],
  ]),
  ...namedSubs("cctv-equipment", [
    ["Cameras", "cctv-cameras", "videocam"],
    ["DVRs & NVRs", "dvr-nvr", "dns"],
    ["Cables & mounts", "cctv-cables-mounts", "cable"],
  ]),
  ...namedSubs(
    "electronics-technology",
    [
      ["Computer & Laptop Repair", "computer-laptop-repair", "laptop"],
      ["Mobile Phone Repair", "mobile-phone-repair", "phone_iphone"],
      ["CCTV Services", "cctv-services", "videocam"],
      ["IT Services", "it-services", "dns"],
      ["Electronics Repair", "electronics-repair", "memory"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("professional-business", [
    ["Office supplies", "office-supplies", "print"],
    ["Printing & Publishing", "printing-publishing", "menu_book"],
  ]),
  ...namedSubs(
    "professional-business",
    [
      ["Chartered Accountants", "chartered-accountants", "calculate"],
      ["Lawyers", "lawyers", "gavel"],
      ["Tax Consultants", "tax-consultants", "request_quote"],
      ["Digital Marketing", "digital-marketing", "campaign"],
      ["Business Consultants", "business-consultants", "handshake"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("health-wellness", [
    ["Medical supplies", "medical-supplies", "medical_services"],
    ["Wellness products", "wellness-products", "spa"],
  ]),
  ...namedSubs(
    "health-wellness",
    [
      ["Dentists", "dentists", "dentistry"],
      ["Hospitals", "hospitals", "local_hospital"],
      ["Clinics", "clinics", "medical_services"],
      ["Physiotherapy", "physiotherapy", "accessibility"],
      ["Beauty Spa", "beauty-spa-wellness", "spa"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("education-training", [
    ["Books & stationery", "books-stationery", "menu_book"],
  ]),
  ...namedSubs(
    "education-training",
    [
      ["Coaching", "coaching", "school"],
      ["Tuition", "tuition", "menu_book"],
      ["Vocational Training", "vocational-training", "engineering"],
      ["Language Training", "language-training", "translate"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("events-lifestyle", [
    ["Jewellery", "jewellery-showrooms", "diamond"],
    ["Decoration materials", "decoration-materials", "celebration"],
    ["Catering supplies", "catering-supplies", "room_service"],
  ]),
  ...namedSubs(
    "events-lifestyle",
    [
      ["Event Organizers", "event-organizers", "event"],
      ["Photographers", "photographers", "photo_camera"],
      ["Videographers", "videographers", "videocam"],
      ["Caterers", "caterers", "room_service"],
      ["Wedding Services", "wedding-services", "favorite"],
      ["Makeup Artists", "makeup-artists", "brush"],
    ],
    { kind: "service", startOrder: 20 },
  ),
  ...namedSubs("logistics-other", [
    ["Packing materials", "packing-materials", "inventory_2"],
    ["Scrap Dealers", "scrap-dealers", "recycling"],
    ["Fabricators", "fabricators", "precision_manufacturing"],
  ]),
  ...namedSubs(
    "logistics-other",
    [
      ["Courier Services", "courier-services", "local_post_office"],
      ["Packers & Movers", "packers-movers", "moving"],
      ["Transporters", "transporters", "local_shipping"],
      ["Security Services", "security-services", "security"],
    ],
    { kind: "service", startOrder: 20 },
  ),

  ...namedSubs(
    "hotels-resorts-stays",
    [
    ["Hotels", "hotels", "hotel"],
    ["Resorts", "resorts", "beach_access"],
    ["Homestays", "homestays", "cottage"],
    ["Villas", "villas", "villa"],
    ["Serviced Apartments", "serviced-apartments", "apartment"],
    ["Guest Houses", "guest-houses", "house"],
    ["Hostels", "hostels", "bunk_bed"],
    ["Boutique Hotels", "boutique-hotels", "nightlife"],
    ["Farm Stays", "farm-stays", "agriculture"],
    ["Cottages", "cottages", "cottage"],
    ["Camping / Glamping", "camping-glamping", "camping"],
    ],
    { kind: "service" },
  ).map((sub) => ({
    ...sub,
    description: `Browse ${sub.name.toLowerCase()} with rooms, rates, facilities, and guest reviews.`,
  })),
  ...namedSubs("rental-hire", [
    ["Vehicle Rental", "vehicle-rental", "directions_car"],
    ["Electronics Rental", "electronics-rental", "devices"],
    ["Event Equipment", "event-equipment", "event"],
    ["Outdoor & Travel", "outdoor-travel", "hiking"],
    ["Tools & Equipment", "tools-equipment", "handyman"],
    ["Furniture Rental", "furniture-rental", "chair"],
  ]).map((sub) => ({
    ...sub,
    description: `Hire ${sub.name.toLowerCase()} by the hour or day — rates, deposits, and availability.`,
  })),
  ...namedSubs("vehicle-rental", [
    ["Car Rental", "car-rental", "directions_car"],
    ["Bike Rental", "bike-rental", "two_wheeler"],
    ["Scooter Rental", "scooter-rental", "electric_moped"],
    ["Van Rental", "van-rental", "airport_shuttle"],
    ["Commercial Vehicle Rental", "commercial-vehicle-rental", "local_shipping"],
  ]),
  ...namedSubs("electronics-rental", [
    ["Camera", "camera-rental", "photo_camera"],
    ["Lens", "lens-rental", "camera_roll"],
    ["Drone", "drone-rental", "flight"],
    ["Projector", "projector-rental", "videocam"],
    ["Laptop", "laptop-rental", "laptop"],
    ["Speaker", "speaker-rental", "speaker"],
  ]),
  ...namedSubs("event-equipment", [
    ["Chairs", "event-chairs", "event_seat"],
    ["Tables", "event-tables", "table_restaurant"],
    ["Sound Systems", "sound-systems", "speaker"],
    ["Lighting", "event-lighting", "lightbulb"],
    ["Party Equipment", "party-equipment", "celebration"],
  ]),
  ...namedSubs("outdoor-travel", [
    ["Camping Equipment", "camping-equipment", "camping"],
    ["Trekking Equipment", "trekking-equipment", "hiking"],
    ["Adventure Equipment", "adventure-equipment", "downhill_skiing"],
  ]),
  ...namedSubs("tools-equipment", [
    ["Power Tools", "power-tools", "handyman"],
    ["Construction Equipment", "construction-equipment", "precision_manufacturing"],
    ["Generators", "generators", "bolt"],
    ["Agricultural Equipment", "agricultural-equipment", "agriculture"],
  ]),
  ...namedSubs("furniture-rental", [
    ["Home Furniture", "home-furniture", "chair"],
    ["Office Furniture", "office-furniture", "desk"],
    ["Event Furniture", "event-furniture", "event_seat"],
  ]),
  ...namedSubs(
    "travel-taxi-transport",
    [
      ["Taxi Services", "taxi-services", "local_taxi"],
      ["Cab Services", "cab-services", "local_taxi"],
      ["Airport Transfers", "airport-transfers", "flight"],
      ["Outstation Taxi", "outstation-taxi", "directions_car"],
      ["Local Taxi", "local-taxi", "local_taxi"],
      ["Bike Taxi", "bike-taxi", "two_wheeler"],
      ["Auto Services", "auto-services", "electric_rickshaw"],
      ["Bus Services", "bus-services", "directions_bus"],
      ["Tour Operators", "tour-operators", "tour"],
      ["Travel Agencies", "travel-agencies", "map"],
      ["Chauffeur Services", "chauffeur-services", "airline_seat_recline_extra"],
    ],
    { kind: "service" },
  ),
];

/** Demo businesses from the previous seed → nearest supplier-first subcategory. */
export const demoBusinessCategoryMap: Record<string, string> = {
  "material-suppliers": "fabricators",
  "architects-builders": "interior-designers",
  "tyre-wheel-services": "car-tyres",
  "battery-services": "car-batteries",
  electrical: "wires-cables",
  "plumbing-items": "pipes-fittings",
  "building-materials": "cement",
  clothing: "clothing-men",
  shoes: "shoes-men",
  "auto-parts": "engine-parts",
  "mobiles-accessories": "phones",
  "computer-hardware": "laptops",
};

export const platformProviderFields: FieldSeed[] = [
  {
    key: "years_of_experience",
    label: "Years of experience",
    fieldType: "number",
    scope: "listing",
    section: "Credentials",
    sortOrder: 1,
    validation: { min: 0, max: 80 },
    placeholder: "e.g. 8",
  },
  {
    key: "business_type",
    label: "Business type",
    fieldType: "select",
    scope: "listing",
    section: "Business",
    sortOrder: 2,
    options: ["Individual", "Small Business", "Company", "Shop", "Agency", "Other"],
  },
  {
    key: "license_number",
    label: "Business license",
    fieldType: "text",
    scope: "listing",
    section: "Documents",
    sortOrder: 3,
    helpText: "Registration or trade license. Super Admin can require this per category.",
    validation: { minLength: 3, maxLength: 64 },
  },
  {
    key: "emergency_service",
    label: "Emergency service",
    fieldType: "boolean",
    scope: "listing",
    section: "Service area",
    sortOrder: 4,
  },
  {
    key: "emergency_timing",
    label: "Emergency service timing",
    fieldType: "text",
    scope: "listing",
    section: "Service area",
    sortOrder: 5,
    placeholder: "e.g. 24/7 or 8pm–8am",
    conditionalRules: { fieldKey: "emergency_service", equals: true },
  },
  {
    key: "home_visit",
    label: "Home visit available",
    fieldType: "boolean",
    scope: "listing",
    section: "Service area",
    sortOrder: 6,
  },
  {
    key: "service_radius_km",
    label: "Service radius (km)",
    fieldType: "number",
    scope: "listing",
    section: "Service area",
    sortOrder: 7,
    validation: { min: 1, max: 500 },
    conditionalRules: { fieldKey: "home_visit", equals: true },
  },
  {
    key: "order_modes",
    label: "Order modes",
    fieldType: "multiselect",
    scope: "listing",
    section: "Wholesale",
    sortOrder: 8,
    options: ["Bulk", "By order", "Single piece"],
    helpText: "How buyers can purchase from this shop.",
  },
  {
    key: "min_order_qty",
    label: "Minimum order quantity",
    fieldType: "number",
    scope: "listing",
    section: "Wholesale",
    sortOrder: 9,
    validation: { min: 1, max: 100000 },
    placeholder: "e.g. 10",
  },
  {
    key: "sells_single_piece",
    label: "Sells single piece",
    fieldType: "boolean",
    scope: "listing",
    section: "Wholesale",
    sortOrder: 10,
  },
  {
    key: "wholesale_available",
    label: "Wholesale rates available",
    fieldType: "boolean",
    scope: "listing",
    section: "Wholesale",
    sortOrder: 11,
  },
  {
    key: "sample_available",
    label: "Samples available",
    fieldType: "boolean",
    scope: "listing",
    section: "Wholesale",
    sortOrder: 12,
  },
  {
    key: "service_area",
    label: "Supply area",
    fieldType: "text",
    scope: "listing",
    section: "Wholesale",
    sortOrder: 13,
    placeholder: "e.g. Kochi & nearby districts, or pan-India shipping",
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 14,
    placeholder: "+91 …",
  },
];

export const platformListingFields: FieldSeed[] = [
  {
    key: "availability",
    label: "Availability",
    fieldType: "select",
    scope: "service",
    section: "Listing",
    sortOrder: 1,
    options: ["Weekdays", "Weekends", "24/7", "By appointment"],
  },
  {
    key: "contact_option",
    label: "Preferred contact",
    fieldType: "select",
    scope: "service",
    section: "Listing",
    sortOrder: 2,
    options: ["Call", "WhatsApp", "Message", "Any"],
  },
  {
    key: "unit",
    label: "Unit",
    fieldType: "text",
    scope: "service",
    section: "Pricing",
    sortOrder: 3,
    placeholder: "e.g. piece, box, metre, kg",
  },
  {
    key: "moq",
    label: "MOQ",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 4,
    validation: { min: 1, max: 100000 },
    placeholder: "Minimum order quantity",
  },
  {
    key: "price_bulk",
    label: "Bulk rate",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 5,
    validation: { min: 0 },
  },
  {
    key: "price_piece",
    label: "Piece rate",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 6,
    validation: { min: 0 },
  },
  {
    key: "brand",
    label: "Brand",
    fieldType: "text",
    scope: "service",
    section: "Catalog",
    sortOrder: 7,
    placeholder: "e.g. UltraTech, ACC, Havells",
    helpText: "Brand name for this catalog item (cement, pipes, phones, etc.).",
  },
  {
    key: "lead_time_days",
    label: "Lead time (days)",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 8,
    validation: { min: 0, max: 365 },
  },
  {
    key: "custom_order",
    label: "Custom / made-to-order",
    fieldType: "boolean",
    scope: "service",
    section: "Pricing",
    sortOrder: 9,
  },
];

export const exampleSubcategoryFields: Record<string, FieldSeed[]> = {
  electrical: [
    {
      key: "product_range",
      label: "Product range",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Catalog",
      sortOrder: 1,
      options: [
        "Wires & cables",
        "Switches & sockets",
        "Lighting",
        "Panels & MCBs",
        "Conduits",
        "Motors",
        "Solar electrical",
      ],
    },
  ],
  "plumbing-items": [
    {
      key: "product_range",
      label: "Product range",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Catalog",
      sortOrder: 1,
      options: ["Pipes & fittings", "Bathroom fittings", "Tanks", "Pumps", "Valves", "Drainage"],
    },
  ],
  clothing: [
    {
      key: "product_range",
      label: "Product range",
      fieldType: "multiselect",
      scope: "listing",
      section: "Catalog",
      sortOrder: 1,
      options: ["Men", "Women", "Kids", "Uniforms", "Fabrics", "Workwear"],
    },
  ],
  shoes: [
    {
      key: "product_range",
      label: "Product range",
      fieldType: "multiselect",
      scope: "listing",
      section: "Catalog",
      sortOrder: 1,
      options: ["Men", "Women", "Kids", "Sports", "Safety footwear", "Casual"],
    },
  ],
  electricians: [
    {
      key: "years_of_experience",
      label: "Years of electrical experience",
      fieldType: "number",
      scope: "listing",
      required: true,
      section: "Credentials",
      sortOrder: 1,
      validation: { min: 0, max: 80 },
    },
    {
      key: "electrical_services",
      label: "Electrical services",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 2,
      options: ["Wiring", "Lighting", "Switchboard", "Inverter", "Solar electrical work"],
    },
    {
      key: "residential_commercial",
      label: "Residential / Commercial",
      fieldType: "select",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 3,
      options: ["Residential", "Commercial", "Both"],
    },
    {
      key: "license_number",
      label: "Electrical license",
      fieldType: "text",
      scope: "listing",
      required: true,
      section: "Documents",
      sortOrder: 4,
      helpText: "Required for electricians.",
    },
    {
      key: "job_type",
      label: "Typical jobs",
      fieldType: "multiselect",
      scope: "service",
      section: "Listing",
      sortOrder: 1,
      options: ["New installation", "Repair", "Maintenance", "Emergency callout"],
    },
  ],
  plumbers: [
    {
      key: "years_of_experience",
      label: "Years of plumbing experience",
      fieldType: "number",
      scope: "listing",
      required: true,
      section: "Credentials",
      sortOrder: 1,
      validation: { min: 0, max: 80 },
    },
    {
      key: "plumbing_services",
      label: "Plumbing services",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 2,
      options: [
        "Pipe installation",
        "Bathroom plumbing",
        "Kitchen plumbing",
        "Water tank",
        "Leakage repair",
        "Drainage",
      ],
    },
    {
      key: "emergency_service",
      label: "Emergency plumbing",
      fieldType: "boolean",
      scope: "listing",
      required: true,
      section: "Service area",
      sortOrder: 3,
    },
  ],
  "interior-designers": [
    {
      key: "years_of_experience",
      label: "Years of design experience",
      fieldType: "number",
      scope: "listing",
      required: true,
      section: "Credentials",
      sortOrder: 1,
      validation: { min: 0, max: 80 },
    },
    {
      key: "residential_commercial",
      label: "Residential / Commercial",
      fieldType: "select",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 2,
      options: ["Residential", "Commercial", "Both"],
    },
    {
      key: "interior_type",
      label: "Interior type",
      fieldType: "multiselect",
      scope: "listing",
      section: "Services",
      sortOrder: 3,
      options: ["2D design", "3D design", "Modular kitchen", "Wardrobe", "Office interior"],
    },
    {
      key: "portfolio",
      label: "Portfolio",
      fieldType: "asset_gallery",
      scope: "listing",
      section: "Media",
      sortOrder: 4,
    },
  ],
  "car-repair-services": [
    {
      key: "years_of_experience",
      label: "Years in auto repair",
      fieldType: "number",
      scope: "listing",
      required: true,
      section: "Credentials",
      sortOrder: 1,
      validation: { min: 0, max: 80 },
    },
    {
      key: "vehicle_types",
      label: "Vehicle types",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 2,
      options: ["Hatchback", "Sedan", "SUV", "Luxury", "Commercial"],
    },
    {
      key: "repair_services",
      label: "Repair services",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 3,
      options: ["General service", "Engine", "AC", "Electrical", "Brake", "Suspension", "Tyres", "Battery"],
    },
    {
      key: "pickup_drop",
      label: "Pickup & drop",
      fieldType: "boolean",
      scope: "listing",
      section: "Service area",
      sortOrder: 4,
    },
  ],
  photographers: [
    {
      key: "photography_type",
      label: "Photography type",
      fieldType: "multiselect",
      scope: "listing",
      required: true,
      section: "Services",
      sortOrder: 1,
      options: ["Wedding", "Portrait", "Product", "Events", "Fashion", "Commercial"],
    },
    {
      key: "offers_video",
      label: "Video",
      fieldType: "boolean",
      scope: "listing",
      section: "Services",
      sortOrder: 2,
    },
    {
      key: "offers_drone",
      label: "Drone",
      fieldType: "boolean",
      scope: "listing",
      section: "Services",
      sortOrder: 3,
    },
    {
      key: "offers_editing",
      label: "Editing included",
      fieldType: "boolean",
      scope: "listing",
      section: "Services",
      sortOrder: 4,
    },
    {
      key: "portfolio",
      label: "Portfolio",
      fieldType: "asset_gallery",
      scope: "listing",
      section: "Media",
      sortOrder: 5,
    },
  ],
  fabricators: [
    {
      key: "availability_qty",
      label: "Availability",
      fieldType: "text",
      scope: "service",
      section: "Listing",
      sortOrder: 10,
    },
    {
      key: "thickness",
      label: "Thickness",
      fieldType: "text",
      scope: "service",
      section: "Listing",
      sortOrder: 11,
    },
    {
      key: "finish",
      label: "Finish",
      fieldType: "text",
      scope: "service",
      section: "Listing",
      sortOrder: 12,
    },
    {
      key: "selection_note",
      label: "Selection",
      fieldType: "text",
      scope: "service",
      section: "Listing",
      sortOrder: 13,
    },
  ],
};

const STAY_HIGHLIGHTED_AMENITIES = [
  "Parking",
  "Bonfire",
  "Indoor Games",
  "Restaurant",
  "Swimming Pool",
  "Breakfast included",
  "Couple friendly",
  "Pet friendly",
];

const STAY_BASIC_FACILITIES = [
  "Parking",
  "Swimming Pool",
  "Power Backup",
  "Housekeeping",
  "Room Service",
  "Newspaper",
  "WiFi",
  "Lift",
  "CCTV",
  "Fire extinguisher",
  "Garden",
  "Play area",
];

const STAY_GENERAL_SERVICES = [
  "Concierge",
  "Multilingual Staff",
  "Luggage Assistance",
  "Caretaker",
  "Pickup & drop",
  "Pool/Beach towels",
];

const STAY_WELLNESS_AMENITIES = [
  "First-aid Services",
  "Spa",
  "Gym",
  "Yoga",
  "Doctor on call",
];

const STAY_ROOM_AMENITIES = [
  "Coffee Machine",
  "Dental Kit",
  "Geyser/Water Heater",
  "Toiletries",
  "Air Purifier",
  "Work Desk",
  "Air conditioning",
  "TV",
  "WiFi",
  "Balcony",
  "Kitchenette",
  "Private bathroom",
  "Hot water",
  "Mini fridge",
  "Mountain view",
  "Pool view",
  "Garden view",
];

const STAY_ACTIVITIES = [
  "Trekking",
  "Bonfire",
  "Boating",
  "Ayurveda",
  "Guided tours",
  "Cultural shows",
  "Fishing",
  "Cycling",
  "Yoga",
  "Kids activities",
];

/** Property-level stay details (listing form) for Hotels, Resorts & Stays. */
export const stayPropertyFields: FieldSeed[] = [
  {
    key: "check_in_time",
    label: "Check-in time",
    fieldType: "text",
    scope: "listing",
    section: "Stay",
    sortOrder: 1,
    placeholder: "e.g. 14:00",
    helpText: "Shown on the property page for arriving guests.",
  },
  {
    key: "check_out_time",
    label: "Check-out time",
    fieldType: "text",
    scope: "listing",
    section: "Stay",
    sortOrder: 2,
    placeholder: "e.g. 11:00",
  },
  {
    key: "min_stay_nights",
    label: "Minimum stay (nights)",
    fieldType: "number",
    scope: "listing",
    section: "Stay",
    sortOrder: 3,
    validation: { min: 1, max: 30 },
    placeholder: "1",
  },
  {
    key: "meals",
    label: "Meals",
    fieldType: "multiselect",
    scope: "listing",
    section: "Stay",
    sortOrder: 4,
    options: ["Breakfast included", "Lunch", "Dinner", "All meals", "None / room only"],
  },
  {
    key: "breakfast_included",
    label: "Breakfast included",
    fieldType: "boolean",
    scope: "listing",
    section: "Stay",
    sortOrder: 5,
    helpText: "Shown with popular amenities, like other stay sites.",
  },
  {
    key: "amenities_highlighted",
    label: "Popular / highlighted amenities",
    fieldType: "multiselect",
    scope: "listing",
    section: "Amenities",
    sortOrder: 6,
    options: STAY_HIGHLIGHTED_AMENITIES,
    helpText: "These appear in the Popular Amenities row on the property and room pages.",
  },
  {
    key: "amenities_basic",
    label: "Basic facilities",
    fieldType: "multiselect",
    scope: "listing",
    section: "Amenities",
    sortOrder: 7,
    options: STAY_BASIC_FACILITIES,
  },
  {
    key: "amenities_services",
    label: "General services",
    fieldType: "multiselect",
    scope: "listing",
    section: "Amenities",
    sortOrder: 8,
    options: STAY_GENERAL_SERVICES,
  },
  {
    key: "amenities_wellness",
    label: "Health and wellness",
    fieldType: "multiselect",
    scope: "listing",
    section: "Amenities",
    sortOrder: 9,
    options: STAY_WELLNESS_AMENITIES,
  },
  {
    key: "couples_allowed",
    label: "Couple friendly",
    fieldType: "boolean",
    scope: "listing",
    section: "House rules",
    sortOrder: 10,
    helpText: "Unmarried couples are welcome.",
  },
  {
    key: "pets_allowed",
    label: "Pet friendly",
    fieldType: "boolean",
    scope: "listing",
    section: "House rules",
    sortOrder: 11,
  },
  {
    key: "extra_bed_available",
    label: "Extra bed available",
    fieldType: "boolean",
    scope: "listing",
    section: "House rules",
    sortOrder: 12,
  },
  {
    key: "extra_bed_rate",
    label: "Extra bed rate (per night)",
    fieldType: "number",
    scope: "listing",
    section: "House rules",
    sortOrder: 13,
    validation: { min: 0 },
    conditionalRules: { fieldKey: "extra_bed_available", equals: true },
  },
  {
    key: "other_activities",
    label: "Other activities",
    fieldType: "multiselect",
    scope: "listing",
    section: "Amenities",
    sortOrder: 14,
    options: STAY_ACTIVITIES,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Stay",
    sortOrder: 15,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "nearest_landmark",
    label: "Nearest landmark",
    fieldType: "text",
    scope: "listing",
    section: "Stay",
    sortOrder: 16,
    placeholder: "e.g. 2 km from Munnar town",
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 17,
    placeholder: "+91 …",
  },
];

/** Each room / cottage / stay option is a Service under the property. */
export const stayRoomFields: FieldSeed[] = [
  {
    key: "room_type",
    label: "Room / stay type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Room",
    sortOrder: 1,
    options: [
      "Deluxe Room",
      "Premium Room",
      "Suite",
      "Family Room",
      "Cottage",
      "Villa",
      "Studio",
      "Dorm",
      "Tent / Glamping",
    ],
  },
  {
    key: "occupancy_adults",
    label: "Max adults",
    fieldType: "number",
    scope: "service",
    required: true,
    section: "Occupancy",
    sortOrder: 2,
    validation: { min: 1, max: 20 },
    placeholder: "e.g. 2",
  },
  {
    key: "occupancy_children",
    label: "Max children",
    fieldType: "number",
    scope: "service",
    section: "Occupancy",
    sortOrder: 3,
    validation: { min: 0, max: 20 },
    placeholder: "e.g. 1",
  },
  {
    key: "bed_type",
    label: "Bed type",
    fieldType: "select",
    scope: "service",
    section: "Room",
    sortOrder: 4,
    options: ["King", "Queen", "Twin", "Double", "Bunk", "Multiple"],
  },
  {
    key: "room_size_sqft",
    label: "Room size (sq ft)",
    fieldType: "number",
    scope: "service",
    section: "Room",
    sortOrder: 5,
    validation: { min: 50, max: 20000 },
  },
  {
    key: "room_count",
    label: "Units of this type",
    fieldType: "number",
    scope: "service",
    section: "Room",
    sortOrder: 6,
    validation: { min: 1, max: 200 },
    helpText: "How many rooms or cottages of this type you can offer.",
  },
  {
    key: "room_facilities",
    label: "Room amenities",
    fieldType: "multiselect",
    scope: "service",
    section: "Room",
    sortOrder: 7,
    options: STAY_ROOM_AMENITIES,
    helpText: "Shown under Room Amenities when a guest opens this room.",
  },
  {
    key: "rate_weekday",
    label: "Weekday rate (per night)",
    fieldType: "number",
    scope: "service",
    required: true,
    section: "Rates",
    sortOrder: 8,
    validation: { min: 0 },
  },
  {
    key: "rate_weekend",
    label: "Weekend rate (per night)",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 9,
    validation: { min: 0 },
    helpText: "Leave blank to use the weekday rate.",
  },
  {
    key: "rate_extra_person",
    label: "Extra person rate (per night)",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 10,
    validation: { min: 0 },
  },
  {
    key: "rate_extra_bed",
    label: "Extra bed rate (per night)",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 11,
    validation: { min: 0 },
  },
];

/** Shop-level rental details (listing form) for Rental & Hire vendors. */
export const rentalVendorFields: FieldSeed[] = [
  {
    key: "pickup_hours",
    label: "Pickup hours",
    fieldType: "text",
    scope: "listing",
    section: "Hire",
    sortOrder: 1,
    placeholder: "e.g. 8:00 AM – 7:00 PM",
    helpText: "When customers can collect or return items.",
  },
  {
    key: "delivery_available",
    label: "Delivery available",
    fieldType: "boolean",
    scope: "listing",
    section: "Hire",
    sortOrder: 2,
    helpText: "You can drop items at the customer’s location.",
  },
  {
    key: "delivery_radius_km",
    label: "Delivery radius (km)",
    fieldType: "number",
    scope: "listing",
    section: "Hire",
    sortOrder: 3,
    validation: { min: 1, max: 500 },
    conditionalRules: { fieldKey: "delivery_available", equals: true },
  },
  {
    key: "delivery_fee",
    label: "Delivery fee",
    fieldType: "number",
    scope: "listing",
    section: "Hire",
    sortOrder: 4,
    validation: { min: 0 },
    conditionalRules: { fieldKey: "delivery_available", equals: true },
  },
  {
    key: "id_proof_required",
    label: "ID proof required",
    fieldType: "boolean",
    scope: "listing",
    section: "Hire rules",
    sortOrder: 5,
  },
  {
    key: "damage_policy",
    label: "Damage / deposit policy",
    fieldType: "textarea",
    scope: "listing",
    section: "Hire rules",
    sortOrder: 6,
    placeholder: "How deposits and damage are handled",
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Hire",
    sortOrder: 7,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 8,
    placeholder: "+91 …",
  },
];

/** Independent rental item fields on every Rental & Hire listing (Service). */
export const rentalHireListingFields: FieldSeed[] = [
  {
    key: "item_images",
    label: "Item images",
    fieldType: "asset_gallery",
    scope: "service",
    section: "Item",
    sortOrder: 1,
    helpText: "Each rental item is listed separately, with its own photos.",
  },
  {
    key: "rental_availability",
    label: "Availability",
    fieldType: "select",
    scope: "service",
    section: "Item",
    sortOrder: 2,
    options: ["Available", "Limited", "Booked", "Unavailable"],
  },
  {
    key: "quantity",
    label: "Quantity",
    fieldType: "number",
    scope: "service",
    section: "Item",
    sortOrder: 3,
    validation: { min: 0, max: 10000 },
    placeholder: "e.g. 4",
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 4,
    validation: { min: 0 },
    placeholder: "Leave blank if not offered",
  },
  {
    key: "price_daily",
    label: "Daily rate",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 5,
    validation: { min: 0 },
  },
  {
    key: "price_weekly",
    label: "Weekly rate",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 6,
    validation: { min: 0 },
  },
  {
    key: "price_monthly",
    label: "Monthly rate",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 7,
    validation: { min: 0 },
  },
  {
    key: "security_deposit",
    label: "Security deposit",
    fieldType: "number",
    scope: "service",
    section: "Pricing",
    sortOrder: 8,
    validation: { min: 0 },
  },
  {
    key: "min_rental_duration",
    label: "Minimum rental duration",
    fieldType: "text",
    scope: "service",
    section: "Rental terms",
    sortOrder: 9,
    placeholder: "e.g. 4 hours or 1 day",
  },
  {
    key: "max_rental_duration",
    label: "Maximum rental duration",
    fieldType: "text",
    scope: "service",
    section: "Rental terms",
    sortOrder: 10,
    placeholder: "e.g. 30 days",
  },
  {
    key: "rental_location",
    label: "Pickup / location",
    fieldType: "text",
    scope: "service",
    section: "Rental terms",
    sortOrder: 11,
    placeholder: "Where this item can be collected or delivered",
  },
  {
    key: "item_status",
    label: "Status",
    fieldType: "select",
    scope: "service",
    section: "Item",
    sortOrder: 12,
    options: ["Active", "Inactive", "Maintenance"],
  },
];

/** Operator-level travel details (listing form) for Travel, Taxi & Transport. */
export const travelOperatorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Transport",
    sortOrder: 1,
    placeholder: "e.g. 24 hours or 6:00 AM – 11:00 PM",
  },
  {
    key: "airports_served",
    label: "Airports served",
    fieldType: "text",
    scope: "listing",
    section: "Transport",
    sortOrder: 2,
    placeholder: "e.g. JFK, LGA, EWR",
  },
  {
    key: "airport_transfer",
    label: "Airport transfers",
    fieldType: "boolean",
    scope: "listing",
    section: "Transport",
    sortOrder: 3,
  },
  {
    key: "outstation_available",
    label: "Outstation trips",
    fieldType: "boolean",
    scope: "listing",
    section: "Transport",
    sortOrder: 4,
  },
  {
    key: "fleet_size",
    label: "Fleet size",
    fieldType: "number",
    scope: "listing",
    section: "Transport",
    sortOrder: 5,
    validation: { min: 1, max: 5000 },
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Transport",
    sortOrder: 6,
    placeholder: "e.g. English, Spanish",
  },
  {
    key: "payment_modes",
    label: "Payment modes",
    fieldType: "multiselect",
    scope: "listing",
    section: "Transport",
    sortOrder: 7,
    options: ["Cash", "Card", "UPI", "Bank transfer", "Invoice"],
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Transport",
    sortOrder: 8,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 9,
    placeholder: "+91 …",
  },
];

/** Each vehicle / trip package is a Service under the operator. */
export const travelVehicleFields: FieldSeed[] = [
  {
    key: "vehicle_type",
    label: "Vehicle / trip type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Vehicle",
    sortOrder: 1,
    options: [
      "Sedan",
      "Hatchback",
      "SUV",
      "MUV / MPV",
      "Luxury sedan",
      "Van",
      "Tempo traveller",
      "Bus",
      "Bike",
      "Auto rickshaw",
      "Tour package",
    ],
  },
  {
    key: "seating_capacity",
    label: "Seating capacity",
    fieldType: "number",
    scope: "service",
    required: true,
    section: "Vehicle",
    sortOrder: 2,
    validation: { min: 1, max: 80 },
    placeholder: "e.g. 4",
  },
  {
    key: "ac",
    label: "Air conditioned",
    fieldType: "boolean",
    scope: "service",
    section: "Vehicle",
    sortOrder: 3,
  },
  {
    key: "luggage_capacity",
    label: "Luggage",
    fieldType: "text",
    scope: "service",
    section: "Vehicle",
    sortOrder: 4,
    placeholder: "e.g. 2 large + 2 cabin",
  },
  {
    key: "vehicle_count",
    label: "Vehicles of this type",
    fieldType: "number",
    scope: "service",
    section: "Vehicle",
    sortOrder: 5,
    validation: { min: 1, max: 200 },
  },
  {
    key: "price_per_km",
    label: "Rate per km",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 6,
    validation: { min: 0 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 7,
    validation: { min: 0 },
  },
  {
    key: "price_airport",
    label: "Airport transfer rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 8,
    validation: { min: 0 },
  },
  {
    key: "price_outstation_day",
    label: "Outstation day rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 9,
    validation: { min: 0 },
  },
  {
    key: "night_charge",
    label: "Night charge",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 10,
    validation: { min: 0 },
  },
  {
    key: "waiting_charge",
    label: "Waiting charge (per hour)",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 11,
    validation: { min: 0 },
  },
];

/** Crew-level details for Events & Lifestyle service listings. */
export const eventVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Events",
    sortOrder: 1,
    placeholder: "e.g. By appointment or 10:00 AM – 8:00 PM",
  },
  {
    key: "event_types",
    label: "Event types",
    fieldType: "multiselect",
    scope: "listing",
    section: "Events",
    sortOrder: 2,
    options: ["Wedding", "Corporate", "Birthday", "Engagement", "Festival", "Private dinner", "Photoshoot"],
  },
  {
    key: "travel_radius_km",
    label: "Travel radius (km)",
    fieldType: "number",
    scope: "listing",
    section: "Events",
    sortOrder: 3,
    validation: { min: 1, max: 500 },
  },
  {
    key: "team_size",
    label: "Team size",
    fieldType: "number",
    scope: "listing",
    section: "Events",
    sortOrder: 4,
    validation: { min: 1, max: 500 },
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Events",
    sortOrder: 5,
    placeholder: "e.g. English, Hindi",
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Events",
    sortOrder: 6,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 7,
    placeholder: "+91 …",
  },
];

/** Each event package is a Service under the crew. */
export const eventPackageFields: FieldSeed[] = [
  {
    key: "package_type",
    label: "Package type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Package",
    sortOrder: 1,
    options: [
      "Full event",
      "Photography",
      "Videography",
      "Catering",
      "Decor",
      "Makeup",
      "Entertainment",
      "Coordination",
    ],
  },
  {
    key: "duration_hours",
    label: "Duration (hours)",
    fieldType: "number",
    scope: "service",
    section: "Package",
    sortOrder: 2,
    validation: { min: 1, max: 72 },
  },
  {
    key: "guest_capacity",
    label: "Guest capacity",
    fieldType: "number",
    scope: "service",
    section: "Package",
    sortOrder: 3,
    validation: { min: 1, max: 5000 },
  },
  {
    key: "package_includes",
    label: "Includes",
    fieldType: "text",
    scope: "service",
    section: "Package",
    sortOrder: 4,
    placeholder: "e.g. 2 photographers, album, highlights reel",
  },
  {
    key: "crew_count",
    label: "Crews of this type",
    fieldType: "number",
    scope: "service",
    section: "Package",
    sortOrder: 5,
    validation: { min: 1, max: 50 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 6,
    validation: { min: 0 },
  },
  {
    key: "price_day",
    label: "Day rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 7,
    validation: { min: 0 },
  },
];

/** Operator-level details for Logistics service listings. */
export const logisticsVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Logistics",
    sortOrder: 1,
    placeholder: "e.g. 8:00 AM – 8:00 PM",
  },
  {
    key: "coverage_area",
    label: "Coverage area",
    fieldType: "text",
    scope: "listing",
    section: "Logistics",
    sortOrder: 2,
    placeholder: "e.g. NYC five boroughs, NJ, CT",
  },
  {
    key: "packing_available",
    label: "Packing available",
    fieldType: "boolean",
    scope: "listing",
    section: "Logistics",
    sortOrder: 3,
  },
  {
    key: "insurance_available",
    label: "Insurance available",
    fieldType: "boolean",
    scope: "listing",
    section: "Logistics",
    sortOrder: 4,
  },
  {
    key: "fleet_size",
    label: "Fleet / team size",
    fieldType: "number",
    scope: "listing",
    section: "Logistics",
    sortOrder: 5,
    validation: { min: 1, max: 5000 },
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Logistics",
    sortOrder: 6,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Logistics",
    sortOrder: 7,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 8,
    placeholder: "+91 …",
  },
];

/** Each courier / move / security offering is a Service under the operator. */
export const logisticsOfferingFields: FieldSeed[] = [
  {
    key: "offering_type",
    label: "Service type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Service",
    sortOrder: 1,
    options: [
      "Courier",
      "Local move",
      "Outstation move",
      "Freight",
      "Warehouse",
      "Security shift",
      "Armed escort",
    ],
  },
  {
    key: "vehicle_type",
    label: "Vehicle / unit",
    fieldType: "select",
    scope: "service",
    section: "Service",
    sortOrder: 2,
    options: ["Bike", "Van", "Truck", "Tempo", "Container", "Guard team", "Patrol car"],
  },
  {
    key: "capacity_kg",
    label: "Capacity (kg)",
    fieldType: "number",
    scope: "service",
    section: "Service",
    sortOrder: 3,
    validation: { min: 1, max: 30000 },
  },
  {
    key: "crew_size",
    label: "Crew size",
    fieldType: "number",
    scope: "service",
    section: "Service",
    sortOrder: 4,
    validation: { min: 1, max: 40 },
  },
  {
    key: "vehicle_count",
    label: "Units of this type",
    fieldType: "number",
    scope: "service",
    section: "Service",
    sortOrder: 5,
    validation: { min: 1, max: 200 },
  },
  {
    key: "price_per_km",
    label: "Rate per km",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 6,
    validation: { min: 0 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 7,
    validation: { min: 0 },
  },
  {
    key: "price_day",
    label: "Day rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 8,
    validation: { min: 0 },
  },
];

/** Provider-level details for Education service listings. */
export const educationVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Education",
    sortOrder: 1,
    placeholder: "e.g. 9:00 AM – 7:00 PM",
  },
  {
    key: "subjects",
    label: "Subjects",
    fieldType: "multiselect",
    scope: "listing",
    section: "Education",
    sortOrder: 2,
    options: ["Exam prep", "School subjects", "Competitive exams", "Soft skills", "Career"],
  },
  {
    key: "modes_offered",
    label: "Modes offered",
    fieldType: "multiselect",
    scope: "listing",
    section: "Education",
    sortOrder: 3,
    options: ["Online", "In-person", "Hybrid"],
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Education",
    sortOrder: 4,
    placeholder: "e.g. English, Hindi",
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Education",
    sortOrder: 5,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 6,
    placeholder: "+91 …",
  },
];

/** Each course / batch is a Service under the education provider. */
export const educationCourseFields: FieldSeed[] = [
  {
    key: "course_type",
    label: "Course type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Course",
    sortOrder: 1,
    options: ["Coaching", "Tuition", "Language", "Vocational", "Workshop"],
  },
  {
    key: "duration_weeks",
    label: "Duration (weeks)",
    fieldType: "number",
    scope: "service",
    section: "Course",
    sortOrder: 2,
    validation: { min: 1, max: 104 },
  },
  {
    key: "batch_size",
    label: "Batch size",
    fieldType: "number",
    scope: "service",
    section: "Course",
    sortOrder: 3,
    validation: { min: 1, max: 200 },
  },
  {
    key: "session_hours",
    label: "Session hours",
    fieldType: "number",
    scope: "service",
    section: "Course",
    sortOrder: 4,
    validation: { min: 0.5, max: 12 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 5,
    validation: { min: 0 },
  },
  {
    key: "price_session",
    label: "Per session",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 6,
    validation: { min: 0 },
  },
  {
    key: "price_course",
    label: "Full course",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 7,
    validation: { min: 0 },
  },
];

/** Provider-level details for Health service listings. */
export const healthVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Health",
    sortOrder: 1,
    placeholder: "e.g. 9:00 AM – 6:00 PM",
  },
  {
    key: "specialties",
    label: "Specialties",
    fieldType: "multiselect",
    scope: "listing",
    section: "Health",
    sortOrder: 2,
    options: ["General", "Dental", "Orthopedic", "Physio", "Skin", "Spa"],
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Health",
    sortOrder: 3,
    placeholder: "e.g. English, Hindi",
  },
  {
    key: "home_visit",
    label: "Home visit",
    fieldType: "boolean",
    scope: "listing",
    section: "Health",
    sortOrder: 4,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Health",
    sortOrder: 5,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 6,
    placeholder: "+91 …",
  },
];

/** Each treatment / package is a Service under the health provider. */
export const healthServiceFields: FieldSeed[] = [
  {
    key: "treatment_type",
    label: "Treatment type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Treatment",
    sortOrder: 1,
    options: ["Consultation", "Procedure", "Therapy session", "Spa package", "Check-up"],
  },
  {
    key: "duration_minutes",
    label: "Duration (minutes)",
    fieldType: "number",
    scope: "service",
    section: "Treatment",
    sortOrder: 2,
    validation: { min: 5, max: 480 },
  },
  {
    key: "price_session",
    label: "Per session",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 3,
    validation: { min: 0 },
  },
  {
    key: "price_package",
    label: "Package price",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 4,
    validation: { min: 0 },
  },
];

/** Provider-level details for Professional service listings. */
export const professionalVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Professional",
    sortOrder: 1,
    placeholder: "e.g. 10:00 AM – 6:00 PM",
  },
  {
    key: "practice_areas",
    label: "Practice areas",
    fieldType: "multiselect",
    scope: "listing",
    section: "Professional",
    sortOrder: 2,
    options: ["Tax", "Audit", "Corporate", "Litigation", "Marketing", "Strategy"],
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Professional",
    sortOrder: 3,
    placeholder: "e.g. English, Hindi",
  },
  {
    key: "remote_available",
    label: "Remote available",
    fieldType: "boolean",
    scope: "listing",
    section: "Professional",
    sortOrder: 4,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Professional",
    sortOrder: 5,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 6,
    placeholder: "+91 …",
  },
];

/** Each engagement is a Service under the professional. */
export const professionalServiceFields: FieldSeed[] = [
  {
    key: "engagement_type",
    label: "Engagement type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Engagement",
    sortOrder: 1,
    options: ["Consultation", "Retainer", "Project", "Filing", "Campaign"],
  },
  {
    key: "duration_hours",
    label: "Duration (hours)",
    fieldType: "number",
    scope: "service",
    section: "Engagement",
    sortOrder: 2,
    validation: { min: 0.5, max: 200 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 3,
    validation: { min: 0 },
  },
  {
    key: "price_retainer",
    label: "Retainer",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 4,
    validation: { min: 0 },
  },
  {
    key: "price_project",
    label: "Project fee",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 5,
    validation: { min: 0 },
  },
];

/** Home trades (electricians, plumbers, …) — listing-level details. */
export const homeTradeVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Trade",
    sortOrder: 1,
    placeholder: "e.g. 8:00 AM – 7:00 PM",
  },
  {
    key: "job_types",
    label: "Job types",
    fieldType: "multiselect",
    scope: "listing",
    section: "Trade",
    sortOrder: 2,
    options: ["New install", "Repair", "Maintenance", "Emergency", "Renovation"],
  },
  {
    key: "service_radius_km",
    label: "Service radius (km)",
    fieldType: "number",
    scope: "listing",
    section: "Trade",
    sortOrder: 3,
    validation: { min: 1, max: 200 },
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Trade",
    sortOrder: 4,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Trade",
    sortOrder: 5,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 6,
  },
];

/** Packages / job offerings under a home trade listing. */
export const homeTradePackageFields: FieldSeed[] = [
  {
    key: "job_package_type",
    label: "Package type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Package",
    sortOrder: 1,
    options: ["Call-out", "Install", "Repair", "Maintenance", "Full project"],
  },
  {
    key: "duration_hours",
    label: "Typical duration (hours)",
    fieldType: "number",
    scope: "service",
    section: "Package",
    sortOrder: 2,
    validation: { min: 0.5, max: 200 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 3,
    validation: { min: 0 },
  },
  {
    key: "price_job",
    label: "Job / package rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 4,
    validation: { min: 0 },
  },
];

/** Automotive trade listings. */
export const autoTradeVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Workshop",
    sortOrder: 1,
  },
  {
    key: "vehicle_types",
    label: "Vehicle types",
    fieldType: "multiselect",
    scope: "listing",
    section: "Workshop",
    sortOrder: 2,
    options: ["Car", "SUV", "Bike", "Scooter", "Van", "Truck"],
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Workshop",
    sortOrder: 3,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Workshop",
    sortOrder: 4,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 5,
  },
];

export const autoTradePackageFields: FieldSeed[] = [
  {
    key: "job_package_type",
    label: "Service type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Package",
    sortOrder: 1,
    options: ["General service", "Repair", "Detailing", "Wash", "Towing", "Diagnostics"],
  },
  {
    key: "duration_hours",
    label: "Typical duration (hours)",
    fieldType: "number",
    scope: "service",
    section: "Package",
    sortOrder: 2,
    validation: { min: 0.5, max: 72 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 3,
    validation: { min: 0 },
  },
  {
    key: "price_job",
    label: "Job / package rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 4,
    validation: { min: 0 },
  },
];

/** Electronics / IT repair listings. */
export const electronicsTradeVendorFields: FieldSeed[] = [
  {
    key: "service_hours",
    label: "Service hours",
    fieldType: "text",
    scope: "listing",
    section: "Repair",
    sortOrder: 1,
  },
  {
    key: "device_types",
    label: "Device types",
    fieldType: "multiselect",
    scope: "listing",
    section: "Repair",
    sortOrder: 2,
    options: ["Phone", "Laptop", "Desktop", "Tablet", "CCTV", "Printer", "Network"],
  },
  {
    key: "languages",
    label: "Languages",
    fieldType: "text",
    scope: "listing",
    section: "Repair",
    sortOrder: 3,
  },
  {
    key: "cancellation_policy",
    label: "Cancellation policy",
    fieldType: "select",
    scope: "listing",
    section: "Repair",
    sortOrder: 4,
    options: ["Flexible", "Moderate", "Strict", "Non-refundable"],
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    fieldType: "phone",
    scope: "listing",
    section: "Contact",
    sortOrder: 5,
  },
];

export const electronicsTradePackageFields: FieldSeed[] = [
  {
    key: "job_package_type",
    label: "Service type",
    fieldType: "select",
    scope: "service",
    required: true,
    section: "Package",
    sortOrder: 1,
    options: ["Diagnostics", "Screen repair", "Battery", "Software", "Install", "On-site visit"],
  },
  {
    key: "duration_hours",
    label: "Typical duration (hours)",
    fieldType: "number",
    scope: "service",
    section: "Package",
    sortOrder: 2,
    validation: { min: 0.5, max: 72 },
  },
  {
    key: "price_hourly",
    label: "Hourly rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 3,
    validation: { min: 0 },
  },
  {
    key: "price_job",
    label: "Job / package rate",
    fieldType: "number",
    scope: "service",
    section: "Rates",
    sortOrder: 4,
    validation: { min: 0 },
  },
];

export const healthWellnessFields: FieldSeed[] = [
  {
    key: "professional_registration",
    label: "Professional registration",
    fieldType: "text",
    scope: "listing",
    required: true,
    section: "Documents",
    sortOrder: 10,
    helpText: "Medical and wellness providers should include registration or council ID.",
  },
  {
    key: "verification_document",
    label: "Verification document",
    fieldType: "asset_ref",
    scope: "listing",
    section: "Documents",
    sortOrder: 11,
    helpText: "Optional supporting certificate. KYC remains the formal verification path.",
  },
];

function namedSubs(
  parentSlug: string,
  rows: Array<[name: string, slug: string, icon: string]>,
  options?: { kind?: "supplier" | "service"; startOrder?: number },
): SubCategorySeed[] {
  const kind = options?.kind ?? "supplier";
  const startOrder = options?.startOrder ?? 1;
  return rows.map(([name, slug, icon], index) => ({
    name,
    slug,
    parentSlug,
    icon,
    kind,
    sortOrder: startOrder + index,
    description:
      kind === "service"
        ? `Verified ${name.toLowerCase()} ready to take on jobs.`
        : `Shops and wholesalers for ${name.toLowerCase()} — bulk, by order, or single piece.`,
    ...mediaForCategory(parentSlug),
  }));
}
