export const publicUserSelect = {
  id: true,
  name: true,
  email: true,
  phone: true,
  role: true,
  avatarUrl: true,
  emailVerifiedAt: true,
  phoneVerifiedAt: true,
  recoveryEmail: true,
  recoveryEmailVerifiedAt: true,
  mfaEnabled: true,
  disabledAt: true,
  createdAt: true,
} as const;
