import {
  Accessibility,
  Armchair,
  BatteryCharging,
  Tent,
  KeyRound,
  Hotel,
  Palmtree,
  Tractor,
  BedDouble,
  Bus,
  Plane,
  Map,
  Lightbulb,
  Speaker,
  Table,
  Mountain,
  Bike,
  BookOpen,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  CircleDot,
  Cog,
  Cpu,
  Droplets,
  Factory,
  FileText,
  Flower2,
  Gem,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Landmark,
  Languages,
  Laptop,
  LayoutGrid,
  Megaphone,
  Microscope,
  Monitor,
  MoonStar,
  Music,
  Network,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  Printer,
  Receipt,
  Recycle,
  Scale,
  Server,
  Shield,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  Stethoscope,
  Shirt,
  Footprints,
  ShoppingBag,
  Store,
  Truck,
  Users,
  UtensilsCrossed,
  Video,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_BY_KEY: Record<string, LucideIcon> = {
  home_repair_service: Wrench,
  home: Home,
  electrical_services: Zap,
  plumbing: Droplets,
  ac_unit: Snowflake,
  chair: Sofa,
  format_paint: Paintbrush,
  handyman: Hammer,
  weekend: Armchair,
  cleaning_services: Sparkles,
  bug_report: Bug,
  security: Shield,
  apartment: Building2,
  directions_car: Car,
  car_repair: Wrench,
  two_wheeler: Bike,
  car_rental: Car,
  local_car_wash: Droplets,
  rv_hookup: Truck,
  local_shipping: Truck,
  tire_repair: CircleDot,
  battery_charging_full: BatteryCharging,
  devices: Laptop,
  laptop: Laptop,
  phone_iphone: Smartphone,
  language: Globe,
  videocam: Video,
  dns: Server,
  computer: Monitor,
  memory: Cpu,
  lan: Network,
  print: Printer,
  business_center: Briefcase,
  calculate: Calculator,
  gavel: Scale,
  assignment: FileText,
  request_quote: Receipt,
  account_balance: Landmark,
  work: Briefcase,
  groups: Users,
  campaign: Megaphone,
  menu_book: BookOpen,
  handshake: Handshake,
  medical_services: Stethoscope,
  dentistry: Smile,
  spa: Flower2,
  local_hospital: Hospital,
  health_and_safety: HeartPulse,
  accessibility: Accessibility,
  home_health: Home,
  biotech: Microscope,
  self_improvement: HeartPulse,
  school: GraduationCap,
  engineering: Cog,
  psychology: Brain,
  translate: Languages,
  music_note: Music,
  nightlife: PartyPopper,
  palette: Palette,
  interests: Sparkles,
  celebration: PartyPopper,
  event: Calendar,
  photo_camera: Camera,
  room_service: UtensilsCrossed,
  favorite: Heart,
  headphones: Headphones,
  brush: Paintbrush,
  diamond: Gem,
  nights_stay: MoonStar,
  restaurant: UtensilsCrossed,
  checkroom: Shirt,
  steps: Footprints,
  shopping_bag: ShoppingBag,
  settings: Cog,
  inventory_2: Package,
  store: Store,
  local_post_office: Package,
  moving: Boxes,
  recycling: Recycle,
  downhill_skiing: Mountain,
  precision_manufacturing: Factory,
  hotel: Hotel,
  beach_access: Palmtree,
  cottage: Home,
  villa: Hotel,
  house: Home,
  bunk_bed: BedDouble,
  agriculture: Tractor,
  camping: Tent,
  key: KeyRound,
  hiking: Mountain,
  electric_moped: Bike,
  airport_shuttle: Bus,
  camera_roll: Camera,
  flight: Plane,
  speaker: Speaker,
  event_seat: Armchair,
  table_restaurant: Table,
  lightbulb: Lightbulb,
  bolt: Zap,
  desk: Briefcase,
  local_taxi: Car,
  electric_rickshaw: Bike,
  directions_bus: Bus,
  tour: Map,
  map: Map,
  airline_seat_recline_extra: Car,
};

const ICON_BY_SLUG: Record<string, LucideIcon> = {
  electricians: Zap,
  electrical: Zap,
  plumbers: Droplets,
  "plumbing-items": Droplets,
  clothing: Shirt,
  shoes: Footprints,
  "home-decor": Sofa,
  "ac-services": Snowflake,
  "interior-designers": Sofa,
  "painting-contractors": Paintbrush,
  "carpenter-services": Hammer,
  "furniture-repair": Armchair,
  housekeeping: Sparkles,
  "pest-control": Bug,
  "home-security": Shield,
  "real-estate-services": Building2,
};

const FALLBACKS: LucideIcon[] = [
  Store,
  Building2,
  Wrench,
  HeartPulse,
  Briefcase,
  Sparkles,
  Car,
  GraduationCap,
];

export const AllCategoriesIcon = LayoutGrid;

export function iconForCategory(icon?: string | null, slug?: string | null): LucideIcon {
  if (icon && ICON_BY_KEY[icon]) return ICON_BY_KEY[icon];
  if (slug && ICON_BY_SLUG[slug]) return ICON_BY_SLUG[slug];
  const seed = icon || slug;
  if (!seed) return Store;
  let hash = 0;
  for (const char of seed) hash = (hash + char.charCodeAt(0)) % FALLBACKS.length;
  return FALLBACKS[hash] ?? Store;
}
